version: '3.5'
services:

  ers-db:
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
      - ers-pgdata:/var/lib/postgresql/data

volumes:
  ers-pgdata:
    name: ers-pgdata