version: "3.5"
services:

  ers-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ers-db
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
      - ers-pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}

  evaluation-results-service:
    image: evaluation-results-service
    container_name: evaluation-results-service
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      DB_CONTAINER_WAIT: ${DB_CONTAINER_WAIT}
      DB_CONTAINER_WAIT_TIMEOUT: ${DB_CONTAINER_WAIT_TIMEOUT}
    ports:
      - "8081:8080"
    networks:
      - default
    depends_on:
      - ers-db

networks:
  default:
    name: app-network
    driver: bridge

volumes:
  ers-pgdata:
    name: ers-pgdata