version: '3.5'
services:

  ers-db:
    image: postgres:9.6.9
    container_name: ers-db
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
      - /home/ers-pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Novosibirsk"
      PGTZ: "Asia/Novosibirsk"

  evaluation-results-service:
    image: evaluation-results-service
    container_name: evaluation-results-service
    command: ["/wait-for-it.sh", "ers-db:5432", "--timeout=45", "--", "catalina.sh", "run"]
    environment:
      TZ: "Asia/Novosibirsk"
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "9443:9443"
    networks:
      - default
    depends_on:
      - ers-db

networks:
  default:
    name: app-network
    driver: bridge