= Модуль ERS (Evaluation results service)
:toc: macro

== 1. Описание модуля

Evaluation results service представляет собой SOAP веб - сервис, который предназначен для хранения и анализа результатов классификации разнотипных данных с использованием различных алгоритмов классификации, как одиночных так и ансамблевых. Сервис поддерживает хранение таких основных показателей как:

* Точность классификатора
* Дисперсия ошибки классификатора
* Доверительный интервал ошибки классификатора
* Результаты ROC - анализа
* Матрица классификации и др.

Вместе с результами классификации сохраняется полная информация о входных параметрах классификатора, а также обучающая выборка на основе которой была построена модель классификатора.

Сервис также предоставляет API для нахождения оптимальных параметров классификаторов для конкретной обучающей выборки на основе накопленной истории результатов классификации. Наилучшие конфигурации классификаторов выбираются по критерию максимизации точности классификатора.

== 2. Описание формата отправки результатов классификации

=== 2.1. Структура SOAP - запроса отправки результатов классификации

[source,xml]
----
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:evaluation="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header/>
    <soapenv:Body>
        <evaluation:evaluationResultsRequest>
            <evaluation:requestId>611bab87-d40e-44e4-8843-2c5e4faaaceb</evaluation:requestId>
            <evaluation:instances>
                <evaluation:xmlInstances>some-data</evaluation:xmlInstances>
                <evaluation:relationName>iris</evaluation:relationName>
                <evaluation:numInstances>150</evaluation:numInstances>
                <evaluation:numAttributes>5</evaluation:numAttributes>
                <evaluation:numClasses>3</evaluation:numClasses>
                <evaluation:className>Class</evaluation:className>
            </evaluation:instances>
            <evaluation:classifierReport>
                <evaluation:classifierName>CART</evaluation:classifierName>
                <evaluation:classifierDescription>It's decision tree classification algorithm</evaluation:classifierDescription>
                <evaluation:inputOptionsMap>
                    <evaluation:entry>
                        <evaluation:key>minObj</evaluation:key>
                        <evaluation:value>2</evaluation:value>
                    </evaluation:entry>
                    <evaluation:entry>
                        <evaluation:key>maxDepth</evaluation:key>
                        <evaluation:value>5</evaluation:value>
                    </evaluation:entry>
                </evaluation:inputOptionsMap>
                <evaluation:metaClassifier>false</evaluation:metaClassifier>
            </evaluation:classifierReport>
            <evaluation:evaluationMethodReport>
                <evaluation:evaluationMethod>CROSS_VALIDATION</evaluation:evaluationMethod>
                <evaluation:numFolds>10</evaluation:numFolds>
                <evaluation:numTests>10</evaluation:numTests>
            </evaluation:evaluationMethodReport>
            <evaluation:statistics>
                <evaluation:numTestInstances>150</evaluation:numTestInstances>
                <evaluation:numCorrect>135</evaluation:numCorrect>
                <evaluation:numIncorrect>15</evaluation:numIncorrect>
                <evaluation:pctCorrect>98.0</evaluation:pctCorrect>
                <evaluation:pctIncorrect>2.0</evaluation:pctIncorrect>
            </evaluation:statistics>
            <evaluation:classificationCosts>
                <evaluation:className>Iris-setosa</evaluation:className>
                <evaluation:truePositiveRate>0.7843</evaluation:truePositiveRate>
                <evaluation:trueNegativeRate>0.4183</evaluation:trueNegativeRate>
                <evaluation:falsePositiveRate>0.8901</evaluation:falsePositiveRate>
                <evaluation:falseNegativeRate>0.3454</evaluation:falseNegativeRate>
                <evaluation:rocCurve>
                    <evaluation:aucValue>0.9046</evaluation:aucValue>
                    <evaluation:specificity>0.9343</evaluation:specificity>
                    <evaluation:sensitivity>0.7586</evaluation:sensitivity>
                    <evaluation:thresholdValue>0.6268</evaluation:thresholdValue>
                </evaluation:rocCurve>
            </evaluation:classificationCosts>
            <evaluation:confusionMatrix>
                <evaluation:actualClass>Iris-setosa</evaluation:actualClass>
                <evaluation:predictedClass>Iris-versicolor</evaluation:predictedClass>
                <evaluation:numInstances>5</evaluation:numInstances>
            </evaluation:confusionMatrix>
            <evaluation:confusionMatrix>
                <evaluation:actualClass>Iris-setosa</evaluation:actualClass>
                <evaluation:predictedClass>Iris-setosa</evaluation:predictedClass>
                <evaluation:numInstances>56</evaluation:numInstances>
            </evaluation:confusionMatrix>
        </evaluation:evaluationResultsRequest>
    </soapenv:Body>
</soapenv:Envelope>
----

=== 2.2. Описание полей SOAP - запроса отправки результатов классификации

==== 2.2.1. Описание полей блока EvaluationResultsRequest

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса в формате UUID
|Данное поле заполняется клиентским приложением
|2
|instances
|InstancesReport
|+
|Блок содержит информацию об обучающей выборке, на основе которой были получены результаты классификации
|
|3
|classifierReport
|ClassifierReport
|+
|Информация о классификаторе
|
|4
|evaluationMethodReport
|EvaluationMethodReport
|+
|Блок содержит информацию о методе оценки точности классификатора
|
|5
|statistics
|StatisticsReport
|+
|Блок с основными показателями точности классификатора
|
|6
|classificationCosts
|ClassificationCostsReport sequence
|-
|Результаты классификации с учетом издержек
|
|7
|confusionMatrix
|ConfusionMatrixReport sequence
|-
|Структура матрицы классификации
|
|===

==== 2.2.2. Описание полей блока InstancesReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Описание|Комментарий
|1
|xmlInstances
|string
|+
|-
|Обучающая выборка
|
|2
|relationName
|string
|+
|255
|Наименовавние данных
|
|3
|numInstances
|integer
|+
|-
|Число объектов обучающей выборки
|
|4
|numAttributes
|integer
|+
|-
|Число атрибутов
|
|5
|numClasses
|integer
|+
|-
|Число классов
|
|6
|className
|string
|+
|255
|Имя атрибута класса
|
|===

==== 2.2.3. Описание полей блока ClassifierReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Описание|Комментарий
|1
|classifierName
|string
|+
|255
|Наименование классификатора
|В качестве имени можно использовать название алгоритма классификации
|2
|options
|string
|+
|-
|Строка с настройками классификатора
|
|3
|classifierDescription
|string
|-
|255
|Дополнительная информация о классификаторе
|
|4
|inputOptionsMap
|ClassifierReport.InputOptionsMap
|-
|-
|Входные параметры классификатора в формате ключ/значение
|
|5
|metaClassifier
|boolean
|+
|-
|Значение равно true, если классификатор является мета - классификатором (используется для алгоритмов семейства Stacking)
|
|===

==== 2.2.4. Описание полей блока EnsembleClassifierReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|individualClassifiers
|ClassifierReport sequence
|-
|Перечень входных параметров базовых классификаторов, которые использовались при построении ансамбля
|
|===

==== 2.2.5. Описание полей блока EvaluationMethodReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|evaluationMethod
|EvaluationMethod
|+
|Метод оценки точности классификатора
|Заполняется по по справочнику <<Справочник значений EvaluationMethod>>
|2
|numFolds
|integer
|-
|Число блоков для k * V - блочной кросс проверка на тестовой выборке
|
|3
|numTests
|integer
|-
|Число тестов для k * V - блочной кросс проверка на тестовой выборке
|
|4
|seed
|integer
|-
|Начальное значение (seed) для генератор псевдослучайных чисел
|
|===

==== 2.2.6. Описание полей блока StatisticsReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Мин. значение|Макс. значение|Описание|Комментарий
|1
|numTestInstances
|integer
|+
|-
|-
|Число объектов тестовых данных
|
|2
|numCorrect
|integer
|+
|-
|-
|Число верно классифицированных объектов
|
|3
|numIncorrect
|integer
|+
|-
|-
|Число неверно классифицированных объектов
|
|4
|pctCorrect
|decimal
|+
|0
|100
|Точность классификатора
|Доля верно классифицированных объектов
|5
|pctIncorrect
|decimal
|+
|0
|100
|Ошибка классификатора
|Доля неверно классифицированных объектов
|6
|meanAbsoluteError
|decimal
|-
|0
|1
|Средняя абсолютная ошибка классификации
|
|7
|rootMeanSquaredError
|decimal
|-
|0
|1
|Среднеквадратическая ошибка классификации
|
|8
|maxAucValue
|decimal
|-
|0
|1
|Максимальное значение показателя AUC среди всех классов
|
|9
|varianceError
|decimal
|-
|0
|1
|Дисперсия ошибки классификатора
|
|10
|confidenceIntervalLowerBound
|decimal
|-
|0
|1
|Нижняя граница 95% доверительного интервала ошибки классификатора
|
|11
|confidenceIntervalUpperBound
|decimal
|-
|0
|1
|Верхняя граница 95% доверительного интервала ошибки классификатора
|
|===

==== 2.2.7. Описание полей блока ClassificationCostsReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Мин. значение|Макс. значение|Описание|Комментарий
|1
|className
|string
|+
|255
|-
|-
|Наименование класса
|
|2
|truePositiveRate
|decimal
|+
|-
|0
|1
|Доля верно классифицированных положительных примеров для данного класса
|
|3
|falsePositiveRate
|decimal
|+
|-
|0
|1
|Доля отрицательных примеров, классифицированных как положительные
|
|4
|trueNegativeRate
|decimal
|+
|-
|0
|1
|Доля верно классифицированных отрицательных примеров
|
|5
|falseNegativeRate
|decimal
|+
|-
|0
|1
|Доля положительных примеров, классифицированных как отрицательные
|
|6
|rocCurve
|RocCurveReport
|+
|Данные ROC - анализа
|
|===

==== 2.2.8. Описание полей блока RocCurveReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Мин. значение|Макс. значение|Описание|Комментарий
|1
|aucValue
|decimal
|+
|0
|1
|Значение площади под ROC - кривой для соответствующего класса
|
|2
|specificity
|decimal
|+
|0
|1
|Значение специфичности оптимальной точки ROC - кривой для соответствующего класса
|
|3
|sensitivity
|decimal
|+
|0
|1
|Значение чувствительности оптимальной точки ROC - кривой для соответствующего класса
|
|4
|thresholdValue
|decimal
|+
|0
|1
|Значения оптимальный порога для определения класса
|
|===

==== 2.2.9. Описание полей блока ConfusionMatrixReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Описание|Комментарий
|1
|actualClass
|string
|+
|255
|Реальное значение класса
|
|2
|predictedClass
|string
|+
|255
|Прогнозное значение класса
|
|3
|numInstances
|decimal
|+
|-
|Число объектов
|
|===

== 3. Описание формата ответа на запрос о сохранении результатов классификации

=== 3.1. Структура SOAP - ответа на запрос о сохранении результатов классификации

[source,xml]
----
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <SOAP-ENV:evaluationResultsResponse>
            <SOAP-ENV:requestId>611bab87-d40e-44e4-8843-2c5e4faaaceb</SOAP-ENV:requestId>
            <SOAP-ENV:status>SUCCESS</SOAP-ENV:status>
        </SOAP-ENV:evaluationResultsResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
----

=== 3.2. Описание полей ответа на запрос о сохранении результатов классификации

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса
|Совпадает со значением requestId из запроса
|2
|status
|ResponseStatus
|+
|Статус ответа
|Заполняется по по справочнику <<Справочник значений ResponseStatus>>
|===

== 4. Описание формата запроса на нахождение оптимальных конфигураций классификаторов

=== 4.1. Структура SOAP - запроса на нахождение оптимальных конфигураций классификаторов

[source,xml]
----
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:evaluation="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header/>
    <soapenv:Body>
        <evaluation:classifierOptionsRequest>
            <evaluation:instances>
                <evaluation:xmlInstances>iris</evaluation:xmlInstances>
                <evaluation:relationName>iris</evaluation:relationName>
                <evaluation:numInstances>150</evaluation:numInstances>
                <evaluation:numAttributes>5</evaluation:numAttributes>
                <evaluation:numClasses>3</evaluation:numClasses>
                <evaluation:className>Class</evaluation:className>
            </evaluation:instances>
            <evaluation:evaluationMethodReport>
                <evaluation:evaluationMethod>CROSS_VALIDATION</evaluation:evaluationMethod>
                <evaluation:numFolds>10</evaluation:numFolds>
                <evaluation:numTests>10</evaluation:numTests>
            </evaluation:evaluationMethodReport>
        </evaluation:classifierOptionsRequest>
    </soapenv:Body>
</soapenv:Envelope>
----

=== 4.2. Описание полей запроса на нахождение оптимальных конфигураций классификаторов

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|instances
|InstancesReport
|+
|Блок содержит информацию об обучающей выборке для которой будет осуществлен поиск оптимальных параметров классификаторов
|
|2
|evaluationMethodReport
|EvaluationMethodReport
|+
|Блок содержит информацию о методе оценки точности классификатора
|
|===

== 5. Описание формата ответа на запрос о нахождении оптимальных конфигураций классификаторов

=== 5.1. Структура SOAP - ответа на запрос о нахождении оптимальных конфигураций классификаторов

[source,xml]
----
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <SOAP-ENV:classifierOptionsResponse>
            <SOAP-ENV:requestId>83ea36b3-39be-4593-a736-f2470b2c4542</SOAP-ENV:requestId>
            <SOAP-ENV:classifierReports>
                <SOAP-ENV:classifierName>Logistic</SOAP-ENV:classifierName>
                <SOAP-ENV:options>{"type":"logistic","maxIts":200,"useConjugateGradientDescent":false}
                </SOAP-ENV:options>
                <SOAP-ENV:inputOptionsMap>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Метод поиска минимума:</SOAP-ENV:key>
                        <SOAP-ENV:value>Квазиньютоновский метод</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Максимальное число итераций:</SOAP-ENV:key>
                        <SOAP-ENV:value>200</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                </SOAP-ENV:inputOptionsMap>
                <SOAP-ENV:metaClassifier>false</SOAP-ENV:metaClassifier>
            </SOAP-ENV:classifierReports>
            <SOAP-ENV:classifierReports>
                <SOAP-ENV:classifierName>C45</SOAP-ENV:classifierName>
                <SOAP-ENV:options>
                    {"type":"decision_tree","decisionTreeType":"C45","minObj":2,"maxDepth":0,"randomTree":false,"numRandomAttr":0,"useBinarySplits":false,"useRandomSplits":false,"numRandomSplits":1,"seed":1,"additionalOptions":null}
                </SOAP-ENV:options>
                <SOAP-ENV:inputOptionsMap>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Случайное дерево:</SOAP-ENV:key>
                        <SOAP-ENV:value>false</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Использование случайных расщеплений атрибута:</SOAP-ENV:key>
                        <SOAP-ENV:value>false</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Бинарное дерево:</SOAP-ENV:key>
                        <SOAP-ENV:value>false</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Максиальная глубина дерева:</SOAP-ENV:key>
                        <SOAP-ENV:value>0</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Минимальное число объектов в листе:</SOAP-ENV:key>
                        <SOAP-ENV:value>2</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Начальное значение (Seed)</SOAP-ENV:key>
                        <SOAP-ENV:value>1</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                </SOAP-ENV:inputOptionsMap>
                <SOAP-ENV:metaClassifier>false</SOAP-ENV:metaClassifier>
            </SOAP-ENV:classifierReports>
            <SOAP-ENV:status>SUCCESS</SOAP-ENV:status>
        </SOAP-ENV:classifierOptionsResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
----

=== 5.2. Описание полей ответа на запрос о нахождении оптимальных конфигураций классификаторов

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса
|Генерируется вместе с ответом на запрос
|2
|classifierReports
|ClassifierReport sequence
|+
|Список оптимальных конфигураций классификаторов
|
|3
|status
|ResponseStatus
|+
|Статус ответа
|Заполняется по по справочнику <<Справочник значений ResponseStatus>>
|===

== 6. Описание формата запроса на получение результатов классификации

=== 6.1. Структура SOAP - запроса на получение результатов классификации

[source,xml]
----
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:evaluation="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header/>
    <soapenv:Body>
        <evaluation:getEvaluationResultsRequest>
            <evaluation:requestId>28d60dba-2130-49a5-9502-feae4f496638</evaluation:requestId>
        </evaluation:getEvaluationResultsRequest>
    </soapenv:Body>
</soapenv:Envelope>
----

=== 6.2. Описание полей запроса на получение результатов классификации

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса в формате UUID
|
|===

== 7. Описание формата ответа на запрос о получении результатов классификации

=== 7.1. Структура SOAP - ответа на запрос о получении результатов классификации

[source,xml]
----
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <SOAP-ENV:getEvaluationResultsResponse>
            <SOAP-ENV:requestId>e9223fa5-4eba-4133-b10a-02c18cca706f</SOAP-ENV:requestId>
            <SOAP-ENV:status>SUCCESS</SOAP-ENV:status>
            <SOAP-ENV:instances>
                <SOAP-ENV:xmlInstances>some-data</SOAP-ENV:xmlInstances>
                <SOAP-ENV:relationName>Glass</SOAP-ENV:relationName>
                <SOAP-ENV:numInstances>214</SOAP-ENV:numInstances>
                <SOAP-ENV:numAttributes>10</SOAP-ENV:numAttributes>
                <SOAP-ENV:numClasses>6</SOAP-ENV:numClasses>
                <SOAP-ENV:className>Type</SOAP-ENV:className>
            </SOAP-ENV:instances>
            <SOAP-ENV:classifierReport>
                <SOAP-ENV:classifierName>CART</SOAP-ENV:classifierName>
                <SOAP-ENV:options>{"type":"decision_tree","decisionTreeType":"CART","minObj":2,"maxDepth":0,"randomTree":false,"numRandomAttr":0,"useBinarySplits":true,"useRandomSplits":false,"numRandomSplits":1,"seed":1,"additionalOptions":null}</SOAP-ENV:options>
                <SOAP-ENV:inputOptionsMap>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Случайное дерево:</SOAP-ENV:key>
                        <SOAP-ENV:value>false</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Использование случайных расщеплений атрибута:</SOAP-ENV:key>
                        <SOAP-ENV:value>false</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Бинарное дерево:</SOAP-ENV:key>
                        <SOAP-ENV:value>true</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Максиальная глубина дерева:</SOAP-ENV:key>
                        <SOAP-ENV:value>0</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Минимальное число объектов в листе:</SOAP-ENV:key>
                        <SOAP-ENV:value>2</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                    <SOAP-ENV:entry>
                        <SOAP-ENV:key>Начальное значение (Seed)</SOAP-ENV:key>
                        <SOAP-ENV:value>1</SOAP-ENV:value>
                    </SOAP-ENV:entry>
                </SOAP-ENV:inputOptionsMap>
                <SOAP-ENV:metaClassifier>false</SOAP-ENV:metaClassifier>
            </SOAP-ENV:classifierReport>
            <SOAP-ENV:evaluationMethodReport>
                <SOAP-ENV:evaluationMethod>CROSS_VALIDATION</SOAP-ENV:evaluationMethod>
                <SOAP-ENV:numFolds>10</SOAP-ENV:numFolds>
                <SOAP-ENV:numTests>1</SOAP-ENV:numTests>
                <SOAP-ENV:seed>1</SOAP-ENV:seed>
            </SOAP-ENV:evaluationMethodReport>
            <SOAP-ENV:statistics>
                <SOAP-ENV:numTestInstances>214</SOAP-ENV:numTestInstances>
                <SOAP-ENV:numCorrect>154</SOAP-ENV:numCorrect>
                <SOAP-ENV:numIncorrect>60</SOAP-ENV:numIncorrect>
                <SOAP-ENV:pctCorrect>71.9626</SOAP-ENV:pctCorrect>
                <SOAP-ENV:pctIncorrect>28.0374</SOAP-ENV:pctIncorrect>
                <SOAP-ENV:meanAbsoluteError>0.1090</SOAP-ENV:meanAbsoluteError>
                <SOAP-ENV:rootMeanSquaredError>0.2884</SOAP-ENV:rootMeanSquaredError>
                <SOAP-ENV:maxAucValue>0.8824</SOAP-ENV:maxAucValue>
                <SOAP-ENV:varianceError>0.0066</SOAP-ENV:varianceError>
                <SOAP-ENV:confidenceIntervalLowerBound>0.2224</SOAP-ENV:confidenceIntervalLowerBound>
                <SOAP-ENV:confidenceIntervalUpperBound>0.3384</SOAP-ENV:confidenceIntervalUpperBound>
            </SOAP-ENV:statistics>
            <SOAP-ENV:classificationCosts>
                <SOAP-ENV:classValue>containers</SOAP-ENV:classValue>
                <SOAP-ENV:truePositiveRate>0.7692</SOAP-ENV:truePositiveRate>
                <SOAP-ENV:falsePositiveRate>0.0100</SOAP-ENV:falsePositiveRate>
                <SOAP-ENV:trueNegativeRate>0.9900</SOAP-ENV:trueNegativeRate>
                <SOAP-ENV:falseNegativeRate>0.2308</SOAP-ENV:falseNegativeRate>
                <SOAP-ENV:rocCurve>
                    <SOAP-ENV:aucValue>0.8687</SOAP-ENV:aucValue>
                    <SOAP-ENV:specificity>0.9900</SOAP-ENV:specificity>
                    <SOAP-ENV:sensitivity>0.7692</SOAP-ENV:sensitivity>
                    <SOAP-ENV:thresholdValue>0.8182</SOAP-ENV:thresholdValue>
                </SOAP-ENV:rocCurve>
            </SOAP-ENV:classificationCosts>
            <SOAP-ENV:classificationCosts>
                <SOAP-ENV:classValue>headlamps</SOAP-ENV:classValue>
                <SOAP-ENV:truePositiveRate>0.7931</SOAP-ENV:truePositiveRate>
                <SOAP-ENV:falsePositiveRate>0.0162</SOAP-ENV:falsePositiveRate>
                <SOAP-ENV:trueNegativeRate>0.9838</SOAP-ENV:trueNegativeRate>
                <SOAP-ENV:falseNegativeRate>0.2069</SOAP-ENV:falseNegativeRate>
                <SOAP-ENV:rocCurve>
                    <SOAP-ENV:aucValue>0.8824</SOAP-ENV:aucValue>
                    <SOAP-ENV:specificity>0.9622</SOAP-ENV:specificity>
                    <SOAP-ENV:sensitivity>0.8276</SOAP-ENV:sensitivity>
                    <SOAP-ENV:thresholdValue>0.3333</SOAP-ENV:thresholdValue>
                </SOAP-ENV:rocCurve>
            </SOAP-ENV:classificationCosts>
            <SOAP-ENV:classificationCosts>
                <SOAP-ENV:classValue>tableware</SOAP-ENV:classValue>
                <SOAP-ENV:truePositiveRate>0.5556</SOAP-ENV:truePositiveRate>
                <SOAP-ENV:falsePositiveRate>0.0049</SOAP-ENV:falsePositiveRate>
                <SOAP-ENV:trueNegativeRate>0.9951</SOAP-ENV:trueNegativeRate>
                <SOAP-ENV:falseNegativeRate>0.4444</SOAP-ENV:falseNegativeRate>
                <SOAP-ENV:rocCurve>
                    <SOAP-ENV:aucValue>0.7192</SOAP-ENV:aucValue>
                    <SOAP-ENV:specificity>1.0000</SOAP-ENV:specificity>
                    <SOAP-ENV:sensitivity>0.5556</SOAP-ENV:sensitivity>
                    <SOAP-ENV:thresholdValue>0.6667</SOAP-ENV:thresholdValue>
                </SOAP-ENV:rocCurve>
            </SOAP-ENV:classificationCosts>
            <SOAP-ENV:classificationCosts>
                <SOAP-ENV:classValue>vehic wind float</SOAP-ENV:classValue>
                <SOAP-ENV:truePositiveRate>0.2941</SOAP-ENV:truePositiveRate>
                <SOAP-ENV:falsePositiveRate>0.0558</SOAP-ENV:falsePositiveRate>
                <SOAP-ENV:trueNegativeRate>0.9442</SOAP-ENV:trueNegativeRate>
                <SOAP-ENV:falseNegativeRate>0.7059</SOAP-ENV:falseNegativeRate>
                <SOAP-ENV:rocCurve>
                    <SOAP-ENV:aucValue>0.6687</SOAP-ENV:aucValue>
                    <SOAP-ENV:specificity>0.9036</SOAP-ENV:specificity>
                    <SOAP-ENV:sensitivity>0.4706</SOAP-ENV:sensitivity>
                    <SOAP-ENV:thresholdValue>0.2222</SOAP-ENV:thresholdValue>
                </SOAP-ENV:rocCurve>
            </SOAP-ENV:classificationCosts>
            <SOAP-ENV:classificationCosts>
                <SOAP-ENV:classValue>build wind non-float</SOAP-ENV:classValue>
                <SOAP-ENV:truePositiveRate>0.6974</SOAP-ENV:truePositiveRate>
                <SOAP-ENV:falsePositiveRate>0.1594</SOAP-ENV:falsePositiveRate>
                <SOAP-ENV:trueNegativeRate>0.8406</SOAP-ENV:trueNegativeRate>
                <SOAP-ENV:falseNegativeRate>0.3026</SOAP-ENV:falseNegativeRate>
                <SOAP-ENV:rocCurve>
                    <SOAP-ENV:aucValue>0.7923</SOAP-ENV:aucValue>
                    <SOAP-ENV:specificity>0.8043</SOAP-ENV:specificity>
                    <SOAP-ENV:sensitivity>0.7368</SOAP-ENV:sensitivity>
                    <SOAP-ENV:thresholdValue>0.3333</SOAP-ENV:thresholdValue>
                </SOAP-ENV:rocCurve>
            </SOAP-ENV:classificationCosts>
            <SOAP-ENV:classificationCosts>
                <SOAP-ENV:classValue>build wind float</SOAP-ENV:classValue>
                <SOAP-ENV:truePositiveRate>0.8286</SOAP-ENV:truePositiveRate>
                <SOAP-ENV:falsePositiveRate>0.1458</SOAP-ENV:falsePositiveRate>
                <SOAP-ENV:trueNegativeRate>0.8542</SOAP-ENV:trueNegativeRate>
                <SOAP-ENV:falseNegativeRate>0.1714</SOAP-ENV:falseNegativeRate>
                <SOAP-ENV:rocCurve>
                    <SOAP-ENV:aucValue>0.8298</SOAP-ENV:aucValue>
                    <SOAP-ENV:specificity>0.8750</SOAP-ENV:specificity>
                    <SOAP-ENV:sensitivity>0.8143</SOAP-ENV:sensitivity>
                    <SOAP-ENV:thresholdValue>0.6667</SOAP-ENV:thresholdValue>
                </SOAP-ENV:rocCurve>
            </SOAP-ENV:classificationCosts>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind non-float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>9</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>tableware</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>containers</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>headlamps</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>headlamps</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>23</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>headlamps</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>1</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>vehic wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>5</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>headlamps</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>containers</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>containers</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>vehic wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>headlamps</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>vehic wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>1</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>containers</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>headlamps</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>2</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind non-float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind non-float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>53</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>tableware</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>headlamps</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>containers</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>headlamps</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>1</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>containers</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>containers</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>10</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>vehic wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>tableware</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind non-float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>12</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>vehic wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind non-float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>7</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>vehic wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>headlamps</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>vehic wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>2</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>tableware</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind non-float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>1</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>vehic wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>containers</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind non-float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>tableware</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>1</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>containers</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>containers</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>tableware</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>58</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>tableware</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>2</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>vehic wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>vehic wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>5</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>containers</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind non-float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>2</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>tableware</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind non-float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>containers</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>2</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>tableware</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>tableware</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>5</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind non-float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>vehic wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>7</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>headlamps</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>build wind non-float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>3</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>build wind non-float</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>headlamps</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>1</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>tableware</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>vehic wind float</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>1</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
            <SOAP-ENV:confusionMatrix>
                <SOAP-ENV:actualClass>headlamps</SOAP-ENV:actualClass>
                <SOAP-ENV:predictedClass>tableware</SOAP-ENV:predictedClass>
                <SOAP-ENV:numInstances>0</SOAP-ENV:numInstances>
            </SOAP-ENV:confusionMatrix>
        </SOAP-ENV:getEvaluationResultsResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
----

=== 7.2. Описание полей ответа на запрос о получении результатов классификации

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса
|
|2
|status
|ResponseStatus
|+
|Статус ответа
|Заполняется по по справочнику <<Справочник значений ResponseStatus>>
|3
|instances
|InstancesReport
|+
|Блок содержит информацию об обучающей выборке, на основе которой были получены результаты классификации
|
|4
|classifierReport
|ClassifierReport
|-
|Информация о классификаторе
|
|5
|evaluationMethodReport
|EvaluationMethodReport
|+
|Блок содержит информацию о методе оценки точности классификатора
|
|6
|statistics
|StatisticsReport
|-
|Блок с основными показателями точности классификатора
|
|7
|classificationCosts
|ClassificationCostsReport sequence
|-
|Результаты классификации с учетом издержек
|
|8
|confusionMatrix
|ConfusionMatrixReport sequence
|-
|Структура матрицы классификации
|
|===

== Справочник значений EvaluationMethod

[options="header"]
|===
|№|Значение|Описание
|1
|TRAINING_DATA
|Использование всей обучающей выборки для оценки точности классификатора
|2
|CROSS_VALIDATION
|Метод k * V - блочной кросс проверки на тестовой выборке
|===

== Справочник значений ResponseStatus

[options="header"]
|===
|№|Код ответа|Описание
|1
|SUCCESS
|Операция завершилась успешно
|2
|DUPLICATE_REQUEST_ID
|Данные с таким requestId уже существуют в базе
|3
|DATA_NOT_FOUND
|В БД не найдена обучающая выборка, заданная в запросе
|4
|RESULTS_NOT_FOUND
|Не удалось найти данные для заданных параметров запроса
|===